# Generated by Django 4.1.7 on 2023-03-07 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('name', models.CharField(max_length=10)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('createdDate', models.DateField()),
                ('updatedDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('name', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('staffid', models.IntegerField(primary_key=True, serialize=False)),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stdmgnt.department')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userid', models.AutoField(primary_key=True, serialize=False)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('updatedDate', models.DateTimeField(auto_now_add=True)),
                ('user_type', models.CharField(choices=[(1, 'admin'), (2, 'student'), (3, 'staff')], default=1, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('name', models.CharField(max_length=20)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('departmentid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stdmgnt.department')),
                ('staff', models.ManyToManyField(to='stdmgnt.staff')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('name', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('admnno', models.IntegerField(primary_key=True, serialize=False)),
                ('semester', models.IntegerField()),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stdmgnt.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='stdmgnt.user')),
            ],
        ),
        migrations.AddField(
            model_name='staff',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='stdmgnt.user'),
        ),
    ]
